# PYTORCH
https://github.com/mrdbourke/pytorch-deep-learning

In [1]:
import torch
import torchvision

# version check
torch.__version__
torchvision.__version__

'0.23.0+cpu'

In [2]:
# create a tensor
TESOR= torch.tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [3]:
TESOR.shape

torch.Size([1, 3, 3])

In [4]:
# create a random tensor
random_tensor =  torch.rand(size=(3,5))
random_tensor

tensor([[0.1054, 0.6958, 0.6873, 0.9135, 0.8995],
        [0.9556, 0.3831, 0.5058, 0.4904, 0.7271],
        [0.7263, 0.8451, 0.8132, 0.9432, 0.9400]])

In [5]:
# creating 0 and unit tenros
# 0 tensor
zero_tensor = torch.zeros(size=(2,3))
unit_tensor = torch.ones(size=(2,3))
print(zero_tensor)
print(unit_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])



Creating a range and tensors like
Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use `torch.arange(start, end, step)` to do so.

- **start**: start of range (e.g. 0)
- **end**: end of range (e.g. 10)
- **step**: how many steps in between each value (e.g. 1)

You can also create new tensors with the same shape and type as an existing tensor using functions like `torch.zeros_like()` and `torch.ones_like()`. This is useful for initializing tensors based on the shape of another tensor.

In [6]:
range_tensor = torch.range(start=2 ,end=10 ,step=1)
range_tensor.shape

C:\Users\Samin Chandeepa\AppData\Local\Temp\ipykernel_7908\3780462036.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range_tensor = torch.range(start=2 ,end=10 ,step=1)


torch.Size([9])

## Tensor datatypes

The most common type (and generally the default) is torch.float32 or torch.float.


In [7]:
# https://docs.pytorch.org/docs/stable/tensors.html#data-types

In [8]:
float_32_tensor = torch.tensor(data=[3,4,5]  ,  device= None,dtype=torch.float32,requires_grad=False)
float_32_tensor.dtype , float_32_tensor.shape , float_32_tensor.ndim , float_32_tensor.device

(torch.float32, torch.Size([3]), 1, device(type='cpu'))

### Basic operations

Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).

In [9]:
a =torch.tensor([1,2,3])

In [10]:
# multiply
a*3

# or

a.mul(4)
x =  torch.tensor([[]])
print(x.shape)
torch.multiply(input=a , other=100 ,out=x)
print(x.shape)

torch.Size([1, 0])
torch.Size([3])


### 
The difference between element-wise multiplication and matrix multiplication is the addition of values.

![Alt text](./images/1.png)



In [11]:
# Element wise
b =torch.tensor([1,2,3])
b*b

tensor([1, 4, 9])

In [12]:
# Matrix mul
torch.matmul(b ,b) 

tensor(14)

In [13]:
b =  torch.range(start=1 , end=10000 , step= 30)

C:\Users\Samin Chandeepa\AppData\Local\Temp\ipykernel_7908\2421991759.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  b =  torch.range(start=1 , end=10000 , step= 30)


In [14]:
%%time

val = 0 
for i in range(len(b)):
    val += b[i] * b[i]


val

CPU times: total: 0 ns
Wall time: 7.45 ms


tensor(1.1131e+10)

In [15]:
%%time
torch.matmul(b,b)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(1.1131e+10)

In [16]:

# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
print(tensor_A.shape)
print(tensor_B.T.shape)

torch.Size([3, 2])
torch.Size([2, 3])


In [ ]:
torch.matmul(tensor_A ,  tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# creating a feed fw neural network
torch.manual_seed(22)

linear = torch.nn.Linear(in_features=2 ,out_features=4)

x =  tensor_A

output = linear(x)

print(x.shape)
print(output.shape)

torch.Size([3, 2])
torch.Size([3, 4])


In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [ ]:
# change the tensor data type
tensor_A.dtype

# convert innto  int8
tentsor_A_int = tensor_A.type(torch.int8)

tentsor_A_int.dtype

torch.int8

### Reshaping, stacking, squeezing and unsqueezing tensors

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

![Alt text](./images/2.png)

In [ ]:
# create a new tensor

samin = torch.arange(1 ,7)
samin.shape

torch.Size([6])

In [ ]:
# add extra dimention using >> reashape
samin.reshape(1,6).shape


torch.Size([1, 6])

In [ ]:
# we can view also this will just view

a = samin.view(1,6)

In [ ]:
# # here if we change samin this will change a also

# # lets set all the col (col =2) to 0 

samin = samin.reshape(1, 6)
samin[:, 1] = 0
samin , a


(tensor([[1, 0, 3, 4, 5, 6]]), tensor([[1, 0, 3, 4, 5, 6]]))

In [ ]:
print(f"Previous tensor: {samin}")
print(f"Previous shape: {samin.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = samin.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1, 0, 3, 4, 5, 6]])
Previous shape: torch.Size([1, 6])

New tensor: tensor([1, 0, 3, 4, 5, 6])
New shape: torch.Size([6])



And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1, 0, 3, 4, 5, 6])
Previous shape: torch.Size([6])

New tensor: tensor([[1, 0, 3, 4, 5, 6]])
New shape: torch.Size([1, 6])



You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])


### PyTorch tensors & NumPy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8943, 0.2193, 0.8602, 0.9893],
        [0.5373, 0.3472, 0.3103, 0.0957],
        [0.0393, 0.8610, 0.5790, 0.1874]])

Tensor B:
tensor([[0.3425, 0.3677, 0.1489, 0.5900],
        [0.3737, 0.8146, 0.6690, 0.2247],
        [0.9433, 0.2393, 0.1693, 0.7071]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Just as you might've expected, the tensors come out with different values.

But what if you wanted to create two random tensors with the same values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=433333 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.9775, 0.1055, 0.6294, 0.0536],
        [0.9167, 0.7129, 0.5922, 0.5827],
        [0.4236, 0.9050, 0.7612, 0.8220]])

Tensor D:
tensor([[0.9775, 0.1055, 0.6294, 0.0536],
        [0.9167, 0.7129, 0.5922, 0.5827],
        [0.4236, 0.9050, 0.7612, 0.8220]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Putting tensors (and models) on the GPU

You can put tensors (and models, we'll see this later) on a specific device by calling to(device) on them. Where device is the target device you'd like the tensor (or model) to go to.

In [ ]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

Instead, to get a tensor back to CPU and usable with NumPy we can use Tensor.cpu().

This copies the tensor to CPU memory so it's usable with CPUs.

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])