In [3]:
import tensorflow as tf
import numpy as np

print("TensorFlow version:", tf.__version__)
print("Numpy version:", np.__version__)

TensorFlow version: 2.20.0
Numpy version: 2.3.1


In [3]:
# create some tensors
x = tf.constant([11,2])

In [4]:
x.shape
print(x.ndim)

1


In [5]:
# all the data types
print(tf.dtypes.__dict__.keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__', '_sys', 'experimental', 'DType', 'QUANTIZED_DTYPES', 'as_dtype', 'bfloat16', 'bool', 'complex128', 'complex64', 'double', 'float16', 'float32', 'float64', 'half', 'int16', 'int32', 'int64', 'int8', 'qint16', 'qint32', 'qint8', 'quint16', 'quint8', 'resource', 'string', 'uint16', 'uint32', 'uint64', 'uint8', 'variant', 'cast', 'complex', 'saturate_cast'])


In [6]:
# This is a constant

a = tf.constant([[[12,2,3,3] , [1,2,3,4]]] , dtype= tf.int16)
a.dtype
print(a.shape  , a.ndim)

# This is variable
b =  tf.Variable([[[12,2,3,3] , [1,2,3,4]]] , dtype= tf.int16)
a.dtype
print(a.shape  , a.ndim)

print(a[0][0])

(1, 2, 4) 3
(1, 2, 4) 3
tf.Tensor([12  2  3  3], shape=(4,), dtype=int16)


In [7]:
b[0, 0].assign([1, 2, 3, 4])

<tf.Variable 'UnreadVariable' shape=(1, 2, 4) dtype=int16, numpy=
array([[[1, 2, 3, 4],
        [1, 2, 3, 4]]], dtype=int16)>

In [8]:
# If we need to change some variable we need to asign
c =  tf.Variable([1])
c[0].assign(11111)

<tf.Variable 'UnreadVariable' shape=(1,) dtype=int32, numpy=array([11111], dtype=int32)>

In [9]:
# Create randon tesors
random1 =  tf.random.Generator.from_seed(11)
random1 =  random1.normal(shape= (3,3))

random2 =  tf.random.Generator.from_seed(11)
random2 =  random2.normal(shape= (3,3))

random1 , random2 , random2 == random1


(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638, -0.3652325 ],
        [ 0.61883307, -1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967,  0.37944323]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638, -0.3652325 ],
        [ 0.61883307, -1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967,  0.37944323]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [12]:
# we can create tensors with 1 and 0

ones =  tf.ones(shape=(3,3) , dtype= tf.int16)
zeros =  tf.zeros(shape=(3,3))

ones ,zeros

(<tf.Tensor: shape=(3, 3), dtype=int16, numpy=
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=int16)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>)

In [25]:
# create a numpy array
np_array =  np.arange(0 ,10 ,2 , dtype= np.int64)

# convert  to tensor
np_tensor = tf.constant(np_array)

np_array , np_tensor

(array([0, 2, 4, 6, 8]),
 <tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 2, 4, 6, 8])>)

In [30]:
np_tensor.shape , tf.transpose(np_tensor).shape

(TensorShape([5]), TensorShape([5]))

In [4]:

test_tensor = tf.constant([[1]])
mat = tf.matmul(test_tensor ,tf.transpose(test_tensor))

mat2  = test_tensor @ test_tensor

In [5]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [6]:
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

Here we can see that the 3 matrix dimentions are  not OK for the multiplication , here we can do:
1. reshape()
2. we can transpose()


In [7]:
# get the transpose of Y
Y_transpose =  tf.transpose(Y)
Y_transpose

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [8]:
# now we can do the matrix multiplication
X @ Y_transpose

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [12]:
# also we can use the reshape to change the shape of the tensor
Y_reshaped = tf.reshape(Y , shape=(2,3))
Y_reshaped

# now we can do the matrix multiplication
mat_mul = X @ Y_reshaped

# the dot product
dot_product = tf.tensordot(X , Y_reshaped , axes=1)


mat_mul , dot_product


(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>)


### Getting the absolute value

Sometimes you'll want the absolute values (all values are positive) of elements in your tensors.

```
To do so, you can use tf.abs().

```

In [ ]:
temp = tf.random.Generator.from_seed(11)
temp = temp.normal(shape=(3,3))
temp = tf.constant([-1 , -2])
temp , tf.abs(temp)



(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

### Create a random tensor using Randomm

In [26]:
import numpy as np

random_tensor  = tf.constant(np.random.randint(0, 100, size=(3, 3)))
random_tensor.shape

TensorShape([3, 3])

### Here we can do the calculations

1. Min
2. Max
3. Mean
4. Sum
5. argmax() - find the position of the maximum element in a given tensor.
6. argmin() - find the position of the minimum element in a given tensor.

In [30]:
min_random_tensor = tf.reduce_min(random_tensor)
max_random_tensor = tf.reduce_max(random_tensor)
mean_random_tensor = tf.reduce_mean(random_tensor)
sum_random_tensor = tf.reduce_sum(random_tensor)


# argmin and argmax
argmin_random_tensor = tf.argmin(random_tensor)
argmax_random_tensor = tf.argmax(random_tensor)

print(random_tensor)
min_random_tensor , max_random_tensor , mean_random_tensor , sum_random_tensor , argmin_random_tensor , argmax_random_tensor



tf.Tensor(
[[84 43 11]
 [53 13 72]
 [ 0 60 73]], shape=(3, 3), dtype=int32)


(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=84>,
 <tf.Tensor: shape=(), dtype=int32, numpy=45>,
 <tf.Tensor: shape=(), dtype=int32, numpy=409>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 1, 0])>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 2, 2])>)


### One-hot encoding
If you have a tensor of indicies and would like to one-hot encode it, you can use tf.one_hot().

You should also specify the depth parameter (the level which you want to one-hot encode to).

In [34]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>


Squaring, log, square root¶
Many other common mathematical operations you'd like to perform at some stage, probably exist.

Let's take a look at:

- tf.square() - get the square of every value in a tensor.
- tf.sqrt() - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).
- tf.math.log() - get the natural log of every value in a tensor (elements need to floats).


### Tensors and NumPy
We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors.

Tensors can also be converted to NumPy arrays using:

```
- np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).
- tensor.numpy() - call on a tensor to convert to an ndarray.

```


In [ ]:
# convert numpy array to tensor
j = tf.constant(np.array([0, 1, 2, 3]))
j

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 2, 3])>

In [38]:
# convert tensor to numpy array
np_j = j.numpy() 

# or

np_j2 = np.array(j)

np_j , np_j2

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))


### Using @tf.function

In your TensorFlow adventures, you might come across Python functions which have the decorator @tf.function.

### Lets understand python Decorators

Python decorators allow you to modify or extend the behavior of functions and methods without changing their actual code. When you use a Python decorator, you wrap a function with another function, which takes the original function as an argument and returns its modified version.

here is an example code:

```

def decorator(func):
    def wrapper():
        print("Something is happening before the function is called.")
        func()
        print("Something is happening after the function is called.")
    return wrapper

def say_whee():
    print("Whee!")

say_whee = decorator(say_whee)

---output ---
>>> from hello_decorator import say_whee

>>> say_whee()
Something is happening before the function is called.
Whee!
Something is happening after the function is called.

```




In [40]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [41]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

- If you noticed no difference between the above two functions (the decorated one and the non-decorated one) you'd be right.

- Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.

### Working with GPUS

In [42]:
print(tf.config.list_physical_devices('GPU'))

[]


In [43]:
!nvidia-smi

Thu Feb  5 21:38:06 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.14                 Driver Version: 566.14         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce MX330         WDDM  |   00000000:02:00.0 Off |                  N/A |
| N/A   70C    P0             N/A / 5001W |     111MiB /   2048MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----