In [14]:
import tensorflow as tf
import numpy as np

print("TensorFlow version:", tf.__version__)
print("Numpy version:", np.__version__)

TensorFlow version: 2.19.0
Numpy version: 2.0.2


In [3]:
# create some tensors
x = tf.constant([11,2])

In [4]:
x.shape
print(x.ndim)

1


In [5]:
# all the data types
print(tf.dtypes.__dict__.keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__', '_sys', 'experimental', 'DType', 'QUANTIZED_DTYPES', 'as_dtype', 'bfloat16', 'bool', 'complex128', 'complex64', 'double', 'float16', 'float32', 'float64', 'half', 'int16', 'int32', 'int64', 'int8', 'qint16', 'qint32', 'qint8', 'quint16', 'quint8', 'resource', 'string', 'uint16', 'uint32', 'uint64', 'uint8', 'variant', 'cast', 'complex', 'saturate_cast'])


In [6]:
# This is a constant

a = tf.constant([[[12,2,3,3] , [1,2,3,4]]] , dtype= tf.int16)
a.dtype
print(a.shape  , a.ndim)

# This is variable
b =  tf.Variable([[[12,2,3,3] , [1,2,3,4]]] , dtype= tf.int16)
a.dtype
print(a.shape  , a.ndim)

print(a[0][0])

(1, 2, 4) 3
(1, 2, 4) 3
tf.Tensor([12  2  3  3], shape=(4,), dtype=int16)


In [7]:
b[0, 0].assign([1, 2, 3, 4])

<tf.Variable 'UnreadVariable' shape=(1, 2, 4) dtype=int16, numpy=
array([[[1, 2, 3, 4],
        [1, 2, 3, 4]]], dtype=int16)>

In [8]:
# If we need to change some variable we need to asign
c =  tf.Variable([1])
c[0].assign(11111)

<tf.Variable 'UnreadVariable' shape=(1,) dtype=int32, numpy=array([11111], dtype=int32)>

In [9]:
# Create randon tesors
random1 =  tf.random.Generator.from_seed(11)
random1 =  random1.normal(shape= (3,3))

random2 =  tf.random.Generator.from_seed(11)
random2 =  random2.normal(shape= (3,3))

random1 , random2 , random2 == random1


(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638, -0.3652325 ],
        [ 0.61883307, -1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967,  0.37944323]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638, -0.3652325 ],
        [ 0.61883307, -1.0130816 ,  0.28291714],
        [ 1.2132233 ,  0.46988967,  0.37944323]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [12]:
# we can create tensors with 1 and 0

ones =  tf.ones(shape=(3,3) , dtype= tf.int16)
zeros =  tf.zeros(shape=(3,3))

ones ,zeros

(<tf.Tensor: shape=(3, 3), dtype=int16, numpy=
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=int16)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>)

In [25]:
# create a numpy array
np_array =  np.arange(0 ,10 ,2 , dtype= np.int64)

# convert  to tensor
np_tensor = tf.constant(np_array)

np_array , np_tensor

(array([0, 2, 4, 6, 8]),
 <tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 2, 4, 6, 8])>)

In [30]:
np_tensor.shape , tf.transpose(np_tensor).shape

(TensorShape([5]), TensorShape([5]))

In [33]:

test_tensor = tf.constant([[1]])
mat = tf.matmul(test_tensor ,tf.transpose(test_tensor))

mat2  = test_tensor @ test_tensor